// Used for Burger_Builder
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const RESET_PRICE = 'RESET_PRICE';
// Used for Making an Order (Contact.js)
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const LOADING = 'LOADING';
// User for Fetching Orders from Firebase
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
// Login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SAGA = 'LOGIN_SAGA';
export const LOGOUT = 'LOGOUT';
// SAGAS
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const AUTH_INITIATE_LOGOUT_SAGA = 'AUTH_INITIATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT_SAGA = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE_SAGA = 'AUTH_CHECK_STATE';
export const BURGER_INIT_SAGA = 'BURGER_INIT_SAGA';
export const PURCHASE_BURGER_SAGA = 'PURCHASE_BURGER_SAGA';
export const GET_ORDERS_SAGA = 'GET_ORDERS_SAGA';

